[project]
name = "llm_from_scratch"
version = "0.1.0"
description = "Build LLM from scratch"
readme = "README.md"
requires-python = ">=3.11.8"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.0.2",
    "tensorflow>=2.18.0",
    "tiktoken>=0.9.0",
    "torch>=2.6.0",
    "tqdm>=4.67.1",
]
